positive_compliments = [
    "You're like AI with empathy — smart and deeply kind. 🤖❤️",
    "You're the sparkle in a world full of console logs. ✨",
    "You're smoother than a clean Git merge. 🔀",
    "You're more dependable than a cron job at midnight. ⏰",
    "You radiate joy like RGB on full brightness. 🌈",
    "You're like a perfect pull request — impossible not to approve. ✅",
    "You're more polished than a linter-approved PR. 🧽",
    "You're the cherry-picked commit of excellence. 🍒",
    "You're glowing brighter than a successful deployment. 🚀",
    "You're the missing semicolon that makes everything click. 🧩",
    "You're more iconic than Ctrl + Z in a moment of panic. 💡",
    "You bring good vibes like a fast build with zero errors. ⚡",
    "You're cleaner than auto-formatted code. 🧼",
    "You're the green checkmark we all strive for. ✅",
    "You're like a GPU at rest — cool and powerful. ❄️",
    "You're the soothing hum of a well-ventilated server room. 💨",
    "You're like a perfect API response — consistent and appreciated. 🔄",
    "You're running smoother than a stable release. 📦",
    "You're as rare and beautiful as bug-free legacy code. 🧓✨",
    "You're like well-commented code — easy to understand and helpful. 📝",
    "You’re brighter than a neon IDE in dark mode. 💡",
    "You're more uplifting than green test cases on a Friday. 💚",
    "You're as flawless as a one-line regex that works on the first try. 🎯",
    "You're the uptime in a world of outages. 🌍",
    "You shine like a freshly dusted mechanical keyboard. ✨⌨️",
    "You're more charming than a perfectly responsive UI. 📱💖",
    "You're as cool as a liquid-cooled workstation. ❄️💻",
    "You're the final commit in a flawless sprint. 🏁",
    "You're the harmony in well-named variables. 🎶",
    "You're brighter than a terminal after ""make build success"". 🌞",
    "You're the cheat code for good energy. 🎮",
    "You're like a TypeScript compiler with zero issues. 🧠",
    "You're the custom theme of this world. 🎨",
    "You're better than Butter, even with smooth scrolling. 🧈",
    "You're like markdown with just the right emojis. 🖊️",
    "You're the comment that makes everything clearer. 💬",
    "You're the shortcut to productivity. 🔧",
    "You're the emoji in a changelog. 📋✨",
    "You're like an open-source miracle. 🛠️🎁",
    "You're the autofill to my form — perfectly matched. 📝",
    "You're a cached result in a high-traffic app. Efficient and loved. 💓",
    "You're better than finding the missing semicolon. 🔍",
    "You're the package update that doesn't break anything. 📦🎉",
    "You're a debug session that ends in victory. 🧠🔥",
    "You're like an SSD boot — fast and exciting. ⚡🖥️",
    "You're the good part of every changelog. 📑",
    "You're what dark mode feels like on tired eyes. 🖤",
    "You're a positive return in a world of edge cases. ➕",
    "You're more valuable than production data. 🧾💎",
    "You're like a CLI tool I never knew I needed. 💻✨"
]

neutral_compliments = [
    "You're steady like a stable branch. 🪵",
    "You show up like a heartbeat monitor — calm and consistent. 💓",
    "You're neutral like Switzerland — and just as chill. 🇨🇭",
    "You're the default theme — subtle and reliable. 🎨",
    "You're as balanced as well-indented code. 🧘‍♀️",
    "You're the placeholder text that still feels thoughtful. 📄",
    "You're like a while loop that knows when to exit. ⏳",
    "You're quiet but purposeful — like a background thread. 🔄",
    "You're the keyboard that never misses a keypress. 🎹",
    "You're the status message that keeps things moving. 📢",
    "You're as calm as an idle CPU. 🧠💤",
    "You're a README file — understated but essential. 📘",
    "You're the background job that always succeeds. 👨‍💻",
    "You're like placeholder art in a wireframe — waiting to shine. 🖼️",
    "You're a default return statement — safe and expected. ↩️",
    "You're like safe mode — you may not shine, but you work. 🧰",
    "You're the config file no one touches — respected and reliable. 🗂️",
    "You're quiet, but you hold everything together like glue code. 🧩",
    "You're a reserved keyword — not flashy but vital. 🔑",
    "You're as subtle as a progress bar in the background. 📊",
    "You're the API call that returns 200 but no one logs. 🔙",
    "You're a logging statement at INFO level — seen but not heard. 📝",
    "You're a test case that never fails — not dramatic, but dependable. 🧪",
    "You're like a silent co-pilot in VS Code. 🧠",
    "You're as still as a paused animation. 🎞️",
    "You're the quiet tick of a mechanical watch. ⏱️",
    "You're the refresh button we all forget we need. 🔄",
    "You're a timestamp in the logs — always there, always relevant. ⌚",
    "You're like a YAML file — plain but important. 📄",
    "You're the static asset in a dynamic world. 🧱",
    "You're like Wi-Fi at 2 bars — there, holding on. 📶",
    "You're a compiler warning: subtle, but with value. ⚠️",
    "You're the second monitor of my day — quietly supportive. 🖥️",
    "You're a muted tab — still running, still helping. 🔇",
    "You're like a USB plug that works on the first try — rare and neutral. 🔌",
    "You're like a stable OS update — not exciting, but essential. 🛠️",
    "You're a background sync — low-key necessary. 🔃",
    "You're like pagination — no one loves you, but we need you. 📑",
    "You're the auto-save of human interaction. 💾",
    "You're a conditional with only one path — steady. ➡️",
    "You're the median in a sea of extremes. 🧮",
    "You're like whitespace — overlooked, but structure would collapse without you. ␣",
    "You're the alt-tab of people — quiet multitasker. 🖱️",
    "You're the middle child of brightness settings. 🌗",
    "You're the average frame rate — not flashy, but reliable. 🎮",
    "You're the semicolon in a Java file — required, yet underappreciated. 😌",
    "You're the switch case default — always prepared. 🔁",
    "You're a dropdown with one option — minimal and clear. 🔽",
    "You're like passive voice — always present, rarely noticed. 📚"
]

negative_compliments = [
    "You're not crashing — you're just throwing temporary exceptions. 🧠",
    "You're still compiling, and that's progress. 🔧",
    "You reboot stronger every time — just like good systems. 🔄",
    "You're more resilient than a system in infinite loop recovery. 🔁",
    "You’re still updating, and that’s a win. ⚙️",
    "Even in beta, you show potential. 🧪",
    "You’re healing like a backup restoring one byte at a time. 💾",
    "You're not deprecated — just misunderstood. 📉",
    "You're like bad code on a good day — still learning. 📚",
    "You may blue screen, but at least you’re not giving up. 💙",
    "You’re proof error messages can be beautiful. 💬",
    "You're rebooting your self-worth — one log at a time. 🪛",
    "You're like a failed test — not wrong, just incomplete. 🚧",
    "Even null pointers can be reassigned — you’re not stuck. 🔄",
    "You're patching your bugs — and that’s brave. 🛠️",
    "You're like a downtime alert — noticed and being addressed. 🚨",
    "Even throttled APIs bounce back. 🔁",
    "You're an exception being handled. 🧘",
    "You're not broken — just overclocked and under-rested. 🔥",
    "You're the log entry worth reading. 📄",
    "You're not failing — you're pre-debug. 🧩",
    "You're the downtime between greatness. 🌌",
    "You're refactoring your soul — that's powerful. 🧠",
    "You're recovering memory in a RAM-starved world. 💾",
    "You're the break statement we all need. ⛔",
    "You’re on a hotfix journey — one step at a time. 🔨",
    "You're like unreachable code — waiting to shine. 💡",
    "You’re not obsolete — just pre-release. 📦",
    "You're buffering emotions — that’s okay. 📺",
    "You may be rate-limited now, but you’ll scale again. 📈",
    "You're more stable than you feel. 🛡️",
    "You’re indexing back into happiness. 🔢",
    "You’re an inner class of awesomeness — just needs visibility. 🧱",
    "You’re the slow boot to something amazing. 🖥️",
    "You're not failing silently — you're recovering loudly. 🔊",
    "You're a try-catch with lots of heart. ❤️",
    "You’re an if-else away from breakthrough. 🔍",
    "You’re debugging reality — and that’s heroic. 🧑‍🚀",
    "You’re the console warning that needs no fixing. 🟠",
    "You're the force-push of your own comeback. 🚀",
    "You’re the temp file everyone forgot but needed. 🗂️",
    "You’re reclaiming disk space in life. 💽",
    "You’re memory-safe, even with broken pointers. 🧠",
    "You're journaling like system logs — vulnerable and valid. 📘",
    "You're the uncommitted change we believe in. 🔄",
    "You're the slow query with deep insight. 🔍",
    "You're the recursion that resolves. 🔁",
    "You're running tests on yourself — that’s growth. 🧪",
    "You're the catch block after the chaos. 🧹"
]
